female_names = [
    "Abigail", "Ada", "Adelaide", "Adriana", "Aisha", "Alexandra", "Alice", "Alicia", "Alina", "Alison",
    "Alyssa", "Amanda", "Amelia", "Amy", "Ana", "Andrea", "Angela", "Angelina", "Anita", "Ann",
    "Anna", "Anne", "Annie", "Aria", "Ariana", "Ashley", "Audrey", "Ava", "Barbara", "Beatrice",
    "Bella", "Bernadette", "Beth", "Betty", "Bianca", "Bonnie", "Brenda", "Brianna", "Bridget", "Brittany",
    "Brooke", "Camila", "Candace", "Carla", "Carmen", "Carol", "Caroline", "Cassandra", "Catherine", "Cecilia",
    "Celeste", "Charlotte", "Cheryl", "Chloe", "Christina", "Christine", "Cindy", "Claire", "Clara", "Claudia",
    "Clementine", "Colette", "Cora", "Courtney", "Crystal", "Cynthia", "Daisy", "Dana", "Danielle", "Daphne",
    "Deborah", "Debra", "Denise", "Diana", "Diane", "Donna", "Doris", "Dorothy", "Edith", "Eileen",
    "Elaine", "Eleanor", "Elena", "Eliana", "Elise", "Eliza", "Elizabeth", "Ella", "Ellen", "Ellie",
    "Emily", "Emma", "Erica", "Erin", "Esther", "Eva", "Evelyn", "Faith", "Felicity", "Fiona",
    "Frances", "Francesca", "Gabriella", "Gabrielle", "Gemma", "Genevieve", "Georgia", "Geraldine", "Gillian", "Gina",
    "Gloria", "Grace", "Gwendolyn", "Hannah", "Harriet", "Hayley", "Hazel", "Heather", "Heidi", "Helen",
    "Helena", "Hilary", "Holly", "Hope", "Ida", "Irene", "Iris", "Isabel", "Isabella", "Isabelle",
    "Ivy", "Jacqueline", "Jade", "Jamie", "Jane", "Janet", "Janice", "Jasmine", "Jean", "Jeanne",
    "Jennifer", "Jessica", "Jill", "Joan", "Joanna", "Jocelyn", "Jodi", "Jody", "Joelle", "Johanna",
    "Jolene", "Jordan", "Josephine", "Joy", "Joyce", "Judith", "Judy", "Julia", "Juliana", "Julie",
    "June", "Karen", "Katherine", "Kathleen", "Kathy", "Katie", "Katrina", "Kay", "Kayla", "Keira",
    "Kelly", "Kelsey", "Kendra", "Kerry", "Kim", "Kimberly", "Kristen", "Kristin", "Kristina", "Kylie",
    "Laura", "Lauren", "Leah", "Leila", "Lena", "Leslie", "Lillian", "Lily", "Linda", "Lindsay",
    "Lisa", "Liz", "Lola", "Lori", "Louise", "Lucia", "Lucy", "Lydia", "Lynn", "Mabel",
    "Madeline", "Madison", "Mae", "Maggie", "Mandy", "Marcia", "Margaret", "Maria", "Marianne", "Marie",
    "Marilyn", "Marina", "Marion", "Marissa", "Martha", "Mary", "Matilda", "Maureen", "Megan", "Melanie",
    "Melinda", "Melissa", "Meredith", "Mia", "Michaela", "Michele", "Michelle", "Mildred", "Miranda", "Molly",
    "Monica", "Morgan", "Myra", "Nadia", "Nancy", "Naomi", "Natalia", "Natalie", "Natasha", "Nell",
    "Nina", "Noelle", "Nora", "Norma", "Olivia", "Paige", "Pamela", "Patricia", "Paula", "Pauline",
    "Peggy", "Penelope", "Phoebe", "Pippa", "Priscilla", "Rachel", "Rachelle", "Rae", "Rebecca", "Regina",
    "Renee", "Rita", "Roberta", "Robin", "Rosa", "Rose", "Rosemary", "Ruby", "Ruth", "Sabrina",
    "Sally", "Samantha", "Sandra", "Sara", "Sarah", "Sasha", "Savannah", "Scarlett", "Selena", "Serena",
    "Shannon", "Sharon", "Sheila", "Shelley", "Sherry", "Shirley", "Sienna", "Sierra", "Simone", "Sofia",
    "Sonia", "Sophia", "Sophie", "Stacey", "Stella", "Stephanie", "Sue", "Summer", "Susan", "Suzanne",
    "Sylvia", "Tabitha", "Tamara", "Tanya", "Tara", "Teresa", "Tessa", "Theresa", "Tiffany", "Tina",
    "Tracy", "Trisha", "Ursula", "Valerie", "Vanessa", "Vera", "Veronica", "Victoria", "Violet", "Virginia",
    "Vivian", "Wanda", "Wendy", "Whitney", "Willow", "Winifred", "Xenia", "Yasmin", "Yolanda", "Yvonne",
    "Zara", "Zoe"
]


male_first_names = [
    "Aaron", "Abel", "Abraham", "Adam", "Adrian", "Aiden", "Alan", "Albert", "Alec", "Alexander",
    "Alfred", "Ali", "Allen", "Alvin", "Amir", "Andre", "Andrew", "Andy", "Angel", "Angelo",
    "Anthony", "Antonio", "Archie", "Arlo", "Arnold", "Arthur", "Asher", "Ashton", "Austin", "Avery",
    "Axel", "Barry", "Ben", "Benjamin", "Bennett", "Benny", "Bernard", "Bill", "Billy", "Blake",
    "Bob", "Bobby", "Brad", "Bradley", "Brandon", "Brayden", "Brendan", "Brent", "Brett", "Brian",
    "Bruce", "Bryan", "Bryce", "Bryson", "Caden", "Caleb", "Calvin", "Cameron", "Carl", "Carlos",
    "Carter", "Cary", "Casey", "Cecil", "Cedric", "Chad", "Charles", "Charlie", "Chase", "Chester",
    "Chris", "Christian", "Christopher", "Clarence", "Clark", "Clayton", "Clifford", "Clint", "Clyde", "Cody",
    "Colin", "Collin", "Colton", "Conner", "Connor", "Conor", "Cooper", "Corey", "Cory", "Craig",
    "Curtis", "Cyrus", "Dale", "Dallas", "Damian", "Damien", "Dan", "Daniel", "Danny", "Dante",
    "Daren", "Darin", "Darius", "Darrell", "Darren", "Darryl", "Daryl", "Dave", "David", "Dean",
    "Dennis", "Derek", "Derrick", "Desmond", "Devin", "Devon", "Dexter", "Diego", "Dillon", "Dominic",
    "Dominick", "Don", "Donald", "Donnie", "Donovan", "Doug", "Douglas", "Drake", "Drew", "Duane",
    "Dustin", "Dwayne", "Dwight", "Dylan", "Earl", "Ed", "Eddie", "Edgar", "Edmund", "Edward",
    "Edwin", "Eli", "Elias", "Elijah", "Elliot", "Elliott", "Ellis", "Elmer", "Elvis", "Emerson",
    "Emmett", "Enrique", "Eric", "Erik", "Ernest", "Ethan", "Eugene", "Evan", "Everett", "Ezra",
    "Felix", "Floyd", "Forrest", "Francis", "Frank", "Frankie", "Franklin", "Fred", "Freddie", "Frederick",
    "Gabriel", "Gage", "Galen", "Garrett", "Garry", "Gary", "Gavin", "Gene", "Geoffrey", "George",
    "Gerald", "Gerard", "Gilbert", "Glen", "Glenn", "Gordon", "Grady", "Graham", "Grant", "Grayson",
    "Greg", "Gregg", "Gregory", "Griffin", "Guy", "Hank", "Harold", "Harrison", "Harry", "Harvey",
    "Hayden", "Heath", "Hector", "Henry", "Herbert", "Herman", "Homer", "Howard", "Hugh", "Hunter",
    "Ian", "Ike", "Isaac", "Isaiah", "Ivan", "Jace", "Jack", "Jackson", "Jacob", "Jake",
    "James", "Jamie", "Jared", "Jarrett", "Jarvis", "Jason", "Jasper", "Jay", "Jayden", "Jeff",
    "Jeffery", "Jeffrey", "Jeremiah", "Jeremy", "Jerome", "Jerry", "Jesse", "Jessie", "Jesus", "Jim",
    "Jimmy", "Joe", "Joel", "Joey", "John", "Johnathan", "Johnny", "Jon", "Jonathan", "Jonathon",
    "Jordan", "Jorge", "Jose", "Joseph", "Josh", "Joshua", "Juan", "Julian", "Julius", "Junior",
    "Justin", "Kaden", "Kai", "Kaleb", "Karl", "Keith", "Ken", "Kenneth", "Kenny", "Kent",
    "Kevin", "Kirk", "Kris", "Kristopher", "Kurt", "Kyle", "Lance", "Larry", "Lawrence", "Lee",
    "Leo", "Leon", "Leonard", "Leroy", "Leslie", "Levi", "Lewis", "Liam", "Lincoln", "Lloyd",
    "Logan", "Lonnie", "Loren", "Lorenzo", "Louie", "Louis", "Lucas", "Luis", "Luke", "Luther",
    "Lyndon", "Mack", "Malcolm", "Manny", "Manuel", "Marc", "Marcus", "Mark", "Marlon", "Marshall",
    "Martin", "Marty", "Marvin", "Mason", "Mathew", "Matt", "Matthew", "Maurice", "Max", "Maxwell",
    "Melvin", "Merle", "Micah", "Michael", "Micheal", "Mickey", "Miguel", "Mike", "Miles", "Milton",
    "Mitch", "Mitchell", "Mohamed", "Mohammad", "Mohammed", "Monte", "Monty", "Morgan", "Morris", "Moses",
    "Murray", "Nate", "Nathan", "Nathaniel", "Neal", "Neil", "Nelson", "Nick", "Nickolas", "Nicolas",
    "Nigel", "Noah", "Nolan", "Norman", "Oscar", "Owen", "Parker", "Pat", "Patrick", "Paul",
    "Perry", "Pete", "Peter", "Phil", "Philip", "Phillip", "Pierce", "Preston", "Quentin", "Quincy",
    "Quinn", "Rafael", "Ralph", "Randall", "Randy", "Raphael", "Ray", "Raymond", "Reed", "Reggie", "Reginald",
    "Rene", "Rex", "Reynaldo", "Rhett", "Ricardo", "Richard", "Rick", "Rickey", "Ricky", "Riley",
    "Rob", "Robbie", "Robert", "Roberto", "Robin", "Rocco", "Rocky", "Rod", "Roderick", "Rodney",
    "Roger", "Roland", "Rolando", "Roman", "Ron", "Ronald", "Ronnie", "Rory", "Ross", "Roy",
    "Ruben", "Rudy", "Russ", "Russell", "Ryan", "Sal", "Salvador", "Sam", "Sammy", "Samuel",
    "Sandy", "Saul", "Scott", "Sean", "Sebastian", "Sergio", "Seth", "Shane", "Shannon", "Shaun",
    "Shawn", "Sheldon", "Sherman", "Sidney", "Silas", "Simon", "Solomon", "Spencer", "Stan", "Stanley",
    "Stefan", "Stephan", "Stephen", "Steve", "Steven", "Stewart", "Stuart", "Sylvester", "Tad", "Tanner",
    "Ted", "Teddy", "Terence", "Terrance", "Terrell", "Terrence", "Terry", "Thad", "Thaddeus", "Theodore",
    "Thomas", "Tim", "Timmy", "Timothy", "Titus", "Tobias", "Toby", "Todd", "Tom", "Tommy",
    "Tony", "Trent", "Trenton", "Trevor", "Trey", "Tristan", "Troy", "Ty", "Tyler", "Tyson",
    "Vance", "Vernon", "Victor", "Vince", "Vincent", "Vinnie", "Virgil", "Wade", "Walter", "Warren",
    "Wayne", "Wes", "Wesley", "Weston", "Wilbert", "Wilbur", "Will", "Willard", "William", "Willie",
    "Wilson", "Winston", "Wyatt", "Xavier", "Yusuf", "Zach", "Zachary", "Zachery", "Zane", "Zeke"
]

last_names = [
    "Abbott", "Adams", "Aguilar", "Alexander", "Allen", "Alvarez", "Anderson", "Andrews", "Armstrong", "Arnold", "Atkins", "Austin",
    "Bailey", "Baker", "Ball", "Banks", "Barker", "Barnes", "Barnett", "Barrett", "Bates", "Beck", "Bell", "Bennett", "Berry", "Bishop", "Black", "Booth", "Bowen", "Bowman", "Boyd", "Bradley", "Brady", "Brewer", "Brooks", "Brown", "Bryant", "Buchanan", "Burke", "Burns", "Butler", "Byrd",
    "Caldwell", "Campbell", "Cannon", "Carlson", "Carpenter", "Carr", "Carroll", "Carter", "Casey", "Castillo", "Chambers", "Chapman", "Chavez", "Clark", "Cole", "Coleman", "Collins", "Conner", "Cook", "Cooper", "Cox", "Craig", "Crawford", "Cross", "Cruz", "Cummings", "Cunningham", "Curtis",
    "Dalton", "Daniels", "Davidson", "Davis", "Dawson", "Day", "Dean", "Diaz", "Dixon", "Dodd", "Dominguez", "Douglas", "Doyle", "Drake", "Duncan", "Dunn", "Durham", "Dyer",
    "Edwards", "Elliott", "Ellis", "Evans",
    "Farmer", "Ferguson", "Fernandez", "Fields", "Fisher", "Fleming", "Fletcher", "Flores", "Ford", "Foster", "Fowler", "Fox", "Franklin", "Freeman", "Fuller", "Fuentes",
    "Garcia", "Gardner", "Garrett", "Gibson", "Gilbert", "Gill", "Glover", "Gomez", "Gonzales", "Gonzalez", "Goodman", "Gordon", "Graham", "Grant", "Gray", "Green", "Greene", "Gregory", "Griffin", "Gutierrez",
    "Hale", "Hall", "Hamilton", "Hammond", "Hancock", "Hansen", "Harper", "Harris", "Harrison", "Hart", "Harvey", "Hawkins", "Hayes", "Henderson", "Henry", "Hernandez", "Hicks", "Hill", "Hodges", "Hoffman", "Holland", "Holmes", "Holt", "Hopkins", "Howard", "Howell", "Hubbard", "Hughes", "Hunt", "Hunter", "Hutchinson",
    "Jackson", "James", "Jenkins", "Jensen", "Johnson", "Johnston", "Jones", "Jordan", "Joseph",
    "Kane", "Keller", "Kelley", "Kelly", "Kennedy", "Kim", "King", "Klein", "Knight", "Kramer",
    "Lambert", "Lancaster", "Lane", "Lara", "Larson", "Lawrence", "Lawson", "Lee", "Leonard", "Lewis", "Lindsey", "Little", "Lloyd", "Logan", "Long", "Lopez", "Lucas", "Lynch",
    "Mack", "Madden", "Malone", "Mann", "Manning", "Marsh", "Marshall", "Martin", "Martinez", "Mason", "Matthews", "Maxwell", "May", "Mccoy", "Mcdonald", "Mcfarland", "Mcgee", "Mckinney", "Mclaughlin", "Medina", "Mendez", "Mendoza", "Meyer", "Miller", "Mills", "Mitchell", "Montgomery", "Moore", "Morales", "Moreno", "Morgan", "Morris", "Morrison", "Morton", "Moss", "Mueller", "Munoz", "Murphy", "Murray", "Myers",
    "Nash", "Navarro", "Neal", "Nelson", "Newman", "Nguyen", "Nichols", "Norris",
    "Obrien", "Oconnor", "Oliver", "Olson", "Ortiz", "Owen",
    "Padilla", "Page", "Palmer", "Parker", "Parks", "Parsons", "Patel", "Patrick", "Patterson", "Paul", "Payne", "Pearson", "Pena", "Perez", "Perkins", "Perry", "Peters", "Peterson", "Phillips", "Pierce", "Porter", "Powell", "Powers", "Price",
    "Quinn",
    "Ramirez", "Ramos", "Ray", "Reed", "Reese", "Reid", "Reyes", "Reynolds", "Rhodes", "Richards", "Richardson", "Riley", "Rivera", "Robbins", "Roberts", "Robertson", "Robinson", "Rodriguez", "Rogers", "Romero", "Rose", "Ross", "Roth", "Ruiz", "Russell", "Ryan",
    "Sanchez", "Sanders", "Sandoval", "Santos", "Saunders", "Schmidt", "Schneider", "Schroeder", "Schultz", "Scott", "Sharp", "Shaw", "Shelton", "Shepard", "Sherman", "Silva", "Simmons", "Simpson", "Sims", "Smith", "Snyder", "Solis", "Soto", "Spencer", "Stanley", "Steele", "Stephens", "Stevens", "Stewart", "Stone", "Strickland", "Sullivan", "Summers", "Sutton", "Swanson",
    "Taylor", "Thomas", "Thompson", "Thornton", "Tucker", "Turner",
    "Underwood",
    "Valdez", "Vargas", "Vasquez", "Vaughn", "Vega", "Velasquez", "Vinson", "Vega",
    "Wagner", "Walker", "Wallace", "Walters", "Walton", "Ward", "Warner", "Warren", "Washington", "Watkins", "Watson", "Weaver", "Webb", "Weber", "Webster", "Welch", "Wells", "West", "Wheeler", "White", "Wilcox", "Wilkerson", "Williams", "Willis", "Wilson", "Winters", "Wolf", "Wolfe", "Wood", "Woodard", "Woods", "Wright",
    "Yates", "York", "Young",
    "Zamora", "Zimmerman"
]


item_categories = [
    "Antiques",
    "Apparel",
    "Appliances",
    "Automotive",
    "Baby Products",
    "Books",
    "Computers",
    "Cosmetics",
    "Electronics",
    "Furniture",
    "Garden Supplies",
    "Groceries",
    "Health & Wellness",
    "Home Decor",
    "Jewelry",
    "Kitchenware",
    "Musical Instruments",
    "Office Supplies",
    "Pet Supplies",
    "Shoes",
    "Sporting Goods",
    "Toys",
    "Video Games",
]

antique_sub_categories = [
    "Antique Books",
    "Antique Furniture",
    "Antique Jewelry",
    "Antique Maps",
    "Antique Paintings",
    "Antique Porcelain",
    "Antique Silver",
    "Antique Textiles",
    "Antique Toys",
    "Antique Watches",
    "Art Deco",
    "Art Nouveau",
    "Asian Antiques",
    "Clocks",
    "Coins & Currency",
    "Collectible Glass",
    "Collectible Pottery",
    "Folk Art",
    "Historical Memorabilia",
    "Postcards",
    "Stamps",
    "Vintage Clothing",
    "Vintage Electronics",
    "Vintage Musical Instruments",
]

apparel_subcategories = [
    "Activewear",
    "Children's Clothing",
    "Coats & Jackets",
    "Dresses",
    "Formalwear",
    "Jeans",
    "Lingerie & Sleepwear",
    "Maternity Clothing",
    "Men's Clothing",
    "Outerwear",
    "Pants",
    "Shirts & Tops",
    "Shoes",
    "Shorts",
    "Socks & Hosiery",
    "Suits & Blazers",
    "Sweaters",
    "Swimwear",
    "Underwear",
    "Women's Clothing",
    "Workwear",
]

appliance_subcategories = [
    "Air Conditioners",
    "Blenders & Mixers",
    "Coffee Makers",
    "Dishwashers",
    "Dryers",
    "Freezers",
    "Fridges",
    "Microwaves",
    "Ovens",
    "Stoves & Cooktops",
    "Toasters & Toaster Ovens",
    "Vacuum Cleaners",
    "Washing Machines",
    "Water Heaters",
]

automotive_sub_categories = [
    "Auto Parts",
    "Auto Tools & Equipment",
    "Car Care",
    "Car Electronics",
    "Exterior Accessories",
    "Interior Accessories",
    "Motorcycle Parts & Accessories",
    "Oils & Fluids",
    "Performance Parts",
    "Replacement Parts",
    "RV Parts & Accessories",
    "Tires & Wheels",
    "Truck Parts & Accessories",
]

baby_product_subcategories = [
    "Baby Clothing",
    "Baby Food",
    "Baby Furniture",
    "Baby Safety",
    "Baby Toys",
    "Bath & Skincare",
    "Car Seats",
    "Diapering",
    "Feeding Supplies",
    "Maternity Care",
    "Nursery Decor",
    "Pacifiers & Teethers",
    "Strollers & Prams",
]

book_subcategories = [
    "Art & Photography",
    "Biographies & Memoirs",
    "Business & Money",
    "Children's Books",
    "Comics & Graphic Novels",
    "Computers & Technology",
    "Cookbooks, Food & Wine",
    "Education & Teaching",
    "Fiction",
    "Health, Fitness & Dieting",
    "History",
    "Humor & Entertainment",
    "Literature & Fiction",
    "Mystery, Thriller & Suspense",
    "Non-fiction",
    "Politics & Social Sciences",
    "Reference",
    "Religion & Spirituality",
    "Romance",
    "Science & Math",
    "Science Fiction & Fantasy",
    "Self-Help",
    "Sports & Outdoors",
    "Teen & Young Adult",
    "Travel",
]

computer_subcategories = [
    "Desktops",
    "Laptops",
    "Tablets",
    "Monitors",
    "Keyboards",
    "Mice",
    "Printers",
    "Scanners",
    "Webcams",
    "Networking Equipment",
    "Computer Components",
    "Software",
    "Storage Devices",
    "Gaming Computers",
    "Workstations",
    "Servers",
]

cosmetics_subcategories = [
    "Blush",
    "Bronzer",
    "Concealer",
    "Eyebrow Makeup",
    "Eyeliner",
    "Eyeshadow",
    "Face Powder",
    "Foundation",
    "Highlighter",
    "Lip Gloss",
    "Lipstick",
    "Mascara",
    "Nail Polish",
    "Primer",
    "Setting Spray",
]

electronics_subcategories = [
    "Audio & Home Theater",
    "Cameras & Photography",
    "Car Electronics & GPS",
    "Cell Phones & Accessories",
    "Computers & Tablets",
    "Drones & Tech Toys",
    "Health, Fitness & Beauty Tech",
    "Home Automation & Security",
    "Office Electronics",
    "Portable Audio",
    "Smart Home",
    "Televisions & Home Theater",
    "Video Game Consoles",
    "Wearable Technology",
]

furniture_subcategories = [
    "Beds & Mattresses",
    "Bookcases",
    "Chairs",
    "Desks",
    "Dining Tables",
    "Dressers",
    "Entertainment Centers",
    "Futons",
    "Kids' Furniture",
    "Nightstands",
    "Outdoor Furniture",
    "Recliners",
    "Sofas & Couches",
    "Tables",
    "Wardrobes",
]

garden_supplies_subcategories = [
    "Bird & Wildlife Supplies",
    "Composting",
    "Fertilizers & Chemicals",
    "Garden Decor",
    "Garden Furniture",
    "Garden Tools",
    "Greenhouses",
    "Hydroponics",
    "Irrigation",
    "Landscaping Supplies",
    "Outdoor Lighting",
    "Pest Control",
    "Planters & Pots",
    "Plants & Seeds",
    "Ponds & Water Features",
    "Soils & Mulches",
]

grocery_subcategories = [
    "Bakery",
    "Beverages",
    "Canned Goods",
    "Dairy & Eggs",
    "Deli",
    "Frozen Foods",
    "Fruits & Vegetables",
    "Grains, Pasta & Sides",
    "Meat & Seafood",
    "Organic Foods",
    "Snacks",
    "Spices & Seasonings",
]

health_wellness_subcategories = [
    "Vitamins & Dietary Supplements",
    "Health Care",
    "Wellness & Relaxation",
    "Exercise & Fitness Equipment",
    "Weight Loss Products",
    "Medical Supplies & Equipment",
    "Personal Care Products",
    "Mental Health Resources",
    "Sexual Wellness",
    "Alternative Medicine",
    "Nutrition Bars & Drinks",
    "Health Monitoring Devices",
    "Oral Care",
    "Vision Care",
    "First Aid Supplies",
    "Home Tests",
    "Mobility & Daily Living Aids",
]

home_decor_subcategories = [
    "Artwork",
    "Baskets & Bins",
    "Candles & Holders",
    "Clocks",
    "Curtains & Drapes",
    "Decorative Pillows",
    "Floor Rugs",
    "Framed Photos",
    "Indoor Plants",
    "Lamps & Lighting",
    "Mirrors",
    "Picture Frames",
    "Shelves",
    "Throws & Blankets",
    "Vases",
    "Wall Decor",
]

jewelry_subcategories = [
    "Anklets",
    "Bracelets",
    "Brooches",
    "Charms",
    "Cufflinks",
    "Earrings",
    "Engagement Rings",
    "Necklaces",
    "Pendants",
    "Rings",
    "Watches",
    "Wedding Bands",
]

kitchenware_subcategories = [
    "Cookware",
    "Bakeware",
    "Cutlery",
    "Utensils",
    "Food Storage",
    "Drinkware",
    "Kitchen Appliances",
    "Kitchen Tools",
    "Tableware",
    "Kitchen Linens",
    "Small Appliances",
]

musical_instruments_subcategories = [
    "Guitars",
    "Bass Guitars",
    "Keyboards",
    "Pianos",
    "Drums",
    "Percussion Instruments",
    "Woodwind Instruments",
    "Brass Instruments",
    "String Instruments",
    "Orchestral Instruments",
    "DJ Equipment",
    "Recording Equipment",
    "Amplifiers",
    "Effects Pedals",
    "Accessories",
]

office_supplies_subcategories = [
    "Writing Instruments",
    "Paper Products",
    "Desk Accessories",
    "Filing and Organization",
    "Office Furniture",
    "Presentation Supplies",
    "Binding and Laminating",
    "Calendars and Planners",
    "Labels and Labeling",
    "Printers and Scanners",
    "Office Technology",
    "Shipping and Mail Supplies",
    "Staplers and Punches",
    "Envelopes and Mailers",
    "Storage and Organization",
    "Desk Lighting",
    "Whiteboards and Corkboards",
    "Conference Room Supplies",
    "Cleaning and Janitorial",
    "Breakroom Supplies",
]

pet_supplies_subcategories = [
    "Dog Food",
    "Cat Food",
    "Fish Supplies",
    "Bird Supplies",
    "Small Animal Supplies",
    "Reptile Supplies",
    "Pet Toys",
    "Pet Beds",
    "Pet Carriers",
    "Pet Grooming",
    "Pet Training",
    "Pet Collars and Leashes",
    "Pet Bowls and Feeders",
    "Pet Health and Wellness",
    "Pet Treats",
    "Pet Cleanup and Odor Control",
    "Pet Apparel",
    "Pet Accessories",
]

shoe_subcategories = [
    "Athletic Shoes",
    "Boots",
    "Casual Shoes",
    "Dress Shoes",
    "Sandals",
    "Slippers",
    "Sneakers",
]

sporting_goods_subcategories = [
    "Athletic Clothing",
    "Bicycles",
    "Camping & Hiking",
    "Exercise & Fitness",
    "Fishing",
    "Golf",
    "Hunting",
    "Outdoor Recreation",
    "Team Sports",
    "Water Sports",
]

toy_subcategories = [
    "Action Figures",
    "Board Games",
    "Building Blocks",
    "Dolls",
    "Educational Toys",
    "Outdoor Toys",
    "Puzzles",
    "Remote Control Toys",
    "Ride-On Toys",
    "Sports Toys",
    "Stuffed Animals",
    "Toy Vehicles",
    "Water Toys",
]

video_game_subcategories = [
    "Action",
    "Adventure",
    "Role-Playing",
    "Strategy",
    "Sports",
    "Simulation",
    "Fighting",
    "Shooter",
    "Platform",
    "Racing",
    "Puzzle",
    "Party",
    "Music",
    "Educational",
    "Rhythm",
    "MMORPG",
    "Open World",
    "Stealth",
    "Survival",
    "Horror",
    "Visual Novel",
    "Sandbox",
    "Tactical",
    "Turn-Based",
]
